### ISSUE TITLE
[bug] Weird crash with... Lithium?

### ISSUE THREAD

**Issue by Sunconure11** [ix0rai/bodaciousberries#59] opened 2022-09-26 07:29 UTC
https://bytebin.lucko.me/rPg1YPHvp3

**Comment by Thonkman** [comment] 2022-09-26 12:57
there isnt any information here, and im not clicking a random link. im closing the issue unless you provide more evidence.

**Comment by eristhea** [comment] 2022-09-26 14:03
as per what @Thonkman said, please add more info when you open issues in the future. This is a duplicate of #58.

That said though -- I need more information on reproducing #58, so if you could find me a minimal test case that would be fantastic.

Finally - I've attached a version with a fix to that issue (bodacious_berries-lithium-removed.zip), you can use that while you wait for the coming fix.

**Comment by Sunconure11** [comment] 2022-09-26 17:07
Will test it shortly. Updating various mods ATM. I saw this happen with one other mod, but I forgot which one.

**Comment by Sunconure11** [comment] 2022-09-26 18:10
Will test around to be certain, but the issue only appears in certain worlds.

**Comment by eristhea** [comment] 2022-09-27 01:03
Things that would be really helpful:
- a world download for one that causes the crash
- a minimal set of mods to test with
- more logs (latest.log as well as the crash log)

**Comment by eristhea** [comment] 2022-10-03 01:06
closing as duplicate of #58

**Closed as not planned** 2022-10-03 01:06 UTC
Labels: bug, duplicate, crash
